### ISSUE TITLE
FEATURE: include markdown in puzzle.moth

### ISSUE THREAD

**Issue by pi-rho** [dirtbags/moth#54]
Reason: support alternative clients, pass the source markdown through to the compiled puzzle.moth.

``` yaml
authors:
  - me
  - you
files: []
body: |-
 blah blah
md: |-
 teh source
```

^^^ partial example of puzzle.moth JSON in YAML, because when I ML, I YAML
